kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:14-alpine
    commands:
      - apk update
      - apk add --no-cache git
      - yarn
      - yarn build:prod
  - name: publish
    image: node:14-alpine
    environment:
      CF_API_TOKEN:
        from_secret: cf_api_token
      SENTRY_AUTH_TOKEN:
        from_secret: sentry_token
      SENTRY_ORG: pxlblue
      SENTRY_PROJECT: frontend
    commands:
      - apk update
      - apk add --no-cache git
      - yarn global add @cloudflare/wrangler
      - wrangler publish --env production
      - npm install -g @sentry/cli --unsafe-perm
      - export VERSION=`git rev-parse HEAD`
      - sentry-cli releases set-commits "$VERSION" --auto
      - sentry-cli releases files $VERSION upload-sourcemaps ./build/js
