kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:14-alpine
    commands:
      - apk update
      - apk add --no-cache git
      - yarn
      - yarn build:prod
  - name: publish
    image: node:14-alpine
    environment:
      CF_API_TOKEN:
        from_secret: cf_api_token
      SENTRY_URL: https://sentry.pxl.blue/
      SENTRY_ORG: pxlblue
      SENTRY_PROJECT: frontend
    commands:
      - yarn global add @cloudflare/wrangler
      - wrangler publish --env production
