name = "frontend-dev"
route = "dev.pxl.blue/*"
type = "webpack"
workers_dev = false
account_id = "6e8ea52e2c17a072be7e347cd0745a07"
zone_id = "d2286b4dd900c879c557b313766be46f"

[site]
bucket = "./build"
entry-point = "./"

[env.staging]
name = "frontend-staging"
route = "staging.pxl.blue/*"

[env.master]
name = "frontend"
route = "pxl.blue/*"