name = "frontend-dev"
route = "dev.pxl.blue/*"
type = "webpack"
workers_dev = false
account_id = ""
zone_id = ""

[site]
bucket = "./build"
entry-point = "./"

[env.staging]
name = "frontend-staging"
route = "staging.pxl.blue/*"

[env.production]
name = "frontend"
route = "pxl.blue/*"
kv_namespaces = [
  { binding = "FOO", id = "0d2ac74b498b48028cb68387c421e233" },
  { binding = "BAR", id = "0d8c101e168d03c65bddf4ba75150f33" }
]